### ISSUE TITLE
ModuleNotFoundError: No module named 'connectorx.connectorx_python'

### ISSUE THREAD

**Issue by zandeck** [sfu-db/connector-x#214]
Hello,

I tried importing connectorx in a python interpreter after installing it through pipenv, but I am getting this error.

Python 3.10.0 (default, Dec 16 2021, 16:14:51) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import connectorx as cx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxxxx/.local/share/virtualenvs/xxxxx-py-_L81HEc9/lib/python3.10/site-packages/connectorx/__init__.py", line 3, in <module>
    from .connectorx_python import read_sql as _read_sql
ModuleNotFoundError: No module named 'connectorx.connectorx_python'

**Comment by wangxiaoying** [comment]
Hi @zandeck , are you using Apple M1? We don't have a ready-to-use wheel file for Apple M1 chip on PyPI yet. And compiling source file locally through pip is not supported yet (still in progress). In the mean while you can build the wheel file locally followed by the summary in here: https://github.com/sfu-db/connector-x/issues/186#issuecomment-1013733401

**Comment by bmorris3** [comment]
Hi, I'm facing the same issue, not on M1.

**Comment by bmorris3** [comment]
Hi @wangxiaoying, I'm _not_ running this on M1 but facing the same issue.

**Comment by wangxiaoying** [comment]
> Hi @wangxiaoying, I'm _not_ running this on M1 but facing the same issue.

Hi @bmorris3 , sorry that I misunderstood your message. Right now we only have available wheel files for windows amd64, macos (not including M1) and linux x86_64. You can check whether your system could leverage any of it using older version like 0.2.2 (`pip install connectorx==0.2.2`). If it shows that didn't find a matched version, then you need to build connectorx on your local machine like https://github.com/sfu-db/connector-x/issues/186#issuecomment-1013733401.

**Comment by HyundeokShin** [comment]
I have same issue. I use the Redhat 6 system linun x86_64. I installed the this using pip. python version 3.7. what I can check for the issue?

**Comment by wangxiaoying** [comment]
Hi @HyundeokShin , can you try to install the newest alpha version using pip: `pip install connectorx==0.2.4a8`. If it shows that didn't find a matched version, then you need to build connectorx on your local machine like https://github.com/sfu-db/connector-x/issues/186#issuecomment-1013733401

**Comment by d33bs** [comment]
Hello, thank you for the great work on this library, the performance capabilities are amazing. I'm seeing the same issue as others, and similarly, different than only Mac M1's. None of the available releases via pip appear to work using the following:
- Python 3.7
- Debian
- x86_64

**Comment by wangxiaoying** [comment]
Hi @d33bs , thanks for the report and update. On python 3.7, can you try to specify the newest version (e.g. stable: 0.3.0 or alpha: 0.3.1a1)? https://pypi.org/project/connectorx/#history For old versions we might not have the wheel file for m1 and the source distribution might not work.

**Comment by d33bs** [comment]
Hi @wangxiaoying - thanks for the reply. With Python 3.7, I'm unable to install >= 0.3.0 with pip (it doesn't appear to be an available option). This seems to occur even outside of M1-based systems.

**Comment by PaulRudin** [comment]
I'm getting this on ubuntu x86_64 python 3.11. 
pip install looks like it works, but on import the error occurs. 
Is there a version that works with this setup?

**Comment by mvanaltvorst** [comment]
@PaulRudin I encountered the same problem; I've fixed it by pinning connectorx to release candidate 0.3.2a2:

`pip uninstall connectorx && pip install connectorx==0.3.2a2`

**Comment by riyadparvez** [comment]
I am on Mac M1 arm architecture. I am facing the same error

**Comment by kapilphulwani** [comment]
pip uninstall connectorx && pip install connectorx==0.3.2a2

This works perfectly on apple M2 chip.

**Comment by j0bekt01** [comment]
was anyone able to install this package on arm64? I was able to build the wheel manually, but when I attempted to use pip to install the whl, it did not work, saying it was unavailable for that arch.

**Comment by evbo** [comment]
@j0bekt01 it's available on ARM Mac but many people are running Docker containers (or VMs) on their ARM Mac with Linux, so if you're one of those people then it is not yet available for ARM Linux (see linked issue above)

**Comment by cgagel-PA** [comment]
I'm on windows python 3.12 and had this error and the solutions above didn't work for me. I downgraded my env to python 3.11 and was then able to successfully import the module.

**Comment by KM1604** [comment]
I had the same issue as @cgagel-PA - but it's working for me in 3.12 but not 3.13. I've been unable to isolate the reason it's happening.
