### ISSUE TITLE
read_sql error

### ISSUE THREAD

**Issue by heyuqi1970** [sfu-db/connector-x#239]
I use connectorx  in virtual environment, python version is 3.9.

The following error occurs：
```
 df = cx.read_sql("postgresql://username:passwd@192.168.1.17:5432/Management", "SELECT * FROM public.users")
thread '<unnamed>' panicked at 'not implemented: _text',  
connectorx/src/sources/postgres/typesystem.rs:100:22
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/x/development/.virtualenvs/vaex/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-af47a2be4ccc>", line 1, in <module>
    df = cx.read_sql("postgres://username:passwd@192.168.1.17:5432/Management", "SELECT * from public.users")
  File "/Users/x/development/.virtualenvs/vaex/lib/python3.8/site-packages/connectorx/__init__.py", line 118, in read_sql
    result = _read_sql(
pyo3_runtime.PanicException: not implemented: _text
```

**Comment by wangxiaoying** [comment]
Hi @heyuqi1970 , we do not support text array right now. I will close and redirect  this to this issue: https://github.com/sfu-db/connector-x/issues/121

**Comment by heyuqi1970** [comment]
@wangxiaoying Thanks for your replay. What  types of data are currently supported in the database?

**Comment by wangxiaoying** [comment]
@heyuqi1970 , please check out [here](https://github.com/sfu-db/connector-x/blob/main/Types.md#postgres-redshift) for postgres.

**Comment by heyuqi1970** [comment]
@wangxiaoying  Thank you again, your work has greatly facilitated my data acquisition.
