### ISSUE TITLE
Add duration type when rust support it

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/connector-x#26]
i16, f32/i32, interval, numeric, enum, bytes, char, time, timetz, uuid,

and add test

**Comment by Yizhou150** [comment]
Hi Xiaoying,I’ve just arrived in China and currently I have no VPN and can’t access discord. I haven’t finished the postgres types since last week I was busy with my course deadlines. I’m really sorry about that. I’ll try to submit a PR today for what I have now, by the end of today, which should be Wednesday 9 am in Vancouver. Is that Okay?Sorry about that.Best,Yizhou         
            
                
                    
                            
                                
                            
                            
                                yca375
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        On 03/18/2021 04:19, Xiaoying Wang wrote: 
Assigned #26 to @Yizhou150.

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/sfu-db/connector-agent/issues/26#event-4467425702",
"url": "https://github.com/sfu-db/connector-agent/issues/26#event-4467425702",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by baggiponte** [comment]
Hi! I noticed last day that the `interval` type was not (yet) supported. It might be converted to arrow's `Duration`, am I right?

```python
from __future__ import annotations

import os

import connectorx as cx
from dotenv import load_dotenv

load_dotenv()

user: str | None = os.getenv("POSTGRESQL_USER")
password: str | None = os.getenv("POSTGRESQL_PASSWORD")
host: str | None = os.getenv("POSTGRESQL_HOST")
port: str | None = os.getenv("POSTGRESQL_PORT")
database: str | None = os.getenv("POSTGRESQL_DATABASE")

connection_uri = f"postgres://{user}:{password}@{host}:{port}/{database}"

# get top 10 values from `durata_noleggio` col which is an `interval` type
cx.read_sql(connection_uri, "SELECT durata_noleggio FROM bikemi_data LIMIT 10")
```

>thread '<unnamed>' panicked at 'not implemented: interval', /Users/runner/work/connector-x/connector-x/connectorx/src/sources/postgres/typesystem.rs:100:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/luca/Documents/dev/python-projects/bikemi/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-315024db6d83>", line 18, in <cell line: 18>
    cx.read_sql(connection_uri, "SELECT durata_noleggio FROM bikemi_data LIMIT 10")
  File "/Users/luca/Documents/dev/python-projects/bikemi/.venv/lib/python3.9/site-packages/connectorx/__init__.py", line 224, in read_sql
    result = _read_sql(
pyo3_runtime.PanicException: not implemented: interval

**Comment by wangxiaoying** [comment]
Hi @baggiponte , yes we do not support interval for postgres. The supported types can be found here: https://sfu-db.github.io/connector-x/databases/postgres.html

The reason is that the underlying client driver we use doesn't support interval since there is no corresponding rust type developed: https://github.com/sfackler/rust-postgres/issues/60. We will keep this on track.

**Comment by baggiponte** [comment]
Oh this is interesting - how does rust handle time durations? At this point, I guess it simply doesn't (Btw I thought the issue was solved because I saw the PR merged. Thank you for the nice reply!)

**Comment by wangxiaoying** [comment]
> how does rust handle time durations? At this point, I guess it simply doesn't

Yes, I think it doesn't support durations now.

> Btw I thought the issue was solved because I saw the PR merged.

Which PR do you mean? I think the issue is still open: https://github.com/sfackler/rust-postgres/issues/60?

**Comment by baggiponte** [comment]
I thought #71 (because after that the issue was marked as closed) but in fact in #71 you mention yourself intervals are not supported - sorry
