### ISSUE TITLE
invalid message length: timestamp not drained error

### ISSUE THREAD

**Issue by justbldwn** [sfu-db/connector-x#366]
#### What language are you using?

**Python**

#### What version are you using?

0.3.0

#### What database are you using?

Postgres with mode="cursor"

#### What dataframe are you using?

Pandas

#### Can you describe your bug?

Give a high level description of the bug.

When running `read_sql()` via postgres connection with mode="cursor", multiple tables with a timestamp datatype fail to return data with an error message below.

#### What are the steps to reproduce the behavior?

Create a query string on a table with a timestamp in it, and execute the query via `read_sql()`.

If possible, please include a **minimal simple** example including:

##### Example query / code

```
conn = f"postgres://{username}:{password}@{server}:{port}/{vdm}?sslmode=require"
query = """select [timestamp_col] from table"""

df = cx.read_sql(conn=conn, query=query, protocol="cursor")
```

#### What is the error?

```
Traceback (most recent call last):
  File "~/.../jdv.py", line 56, in query_jdv
    df = cx.read_sql(conn=conn, query=query, protocol="cursor", **kwargs)
  File "~/.../lib/python3.8/site-packages/connectorx/__init__.py", line 257, in read_sql
    result = _read_sql(
RuntimeError: error deserializing column 0: invalid message length: timestamp not drained
```

**Comment by wangxiaoying** [comment]
Hi @justbldwn , it seems like the error happens when the underlying client driver parsing the timestamp [here](https://github.com/sfackler/rust-postgres/blob/38da7fa8fe0067f47b60c147ccdaa214ab5f5211/postgres-protocol/src/types/mod.rs#L379).

Since we have `timestamp` type works fine in the CI test [here](https://github.com/sfu-db/connector-x/blob/main/connectorx-python/connectorx/tests/test_postgres.py#L660) with DDL defined [here](https://github.com/sfu-db/connector-x/blob/main/scripts/postgres.sql#L38). Can you provide a simple example that could reproduce this error (including the DDL for table creation and insert some example data)?

**Comment by justbldwn** [comment]
hi, thanks for the response. after doing some digging, it appears the root cause _most likely_ is coming from timestamp values we're storing in our database go into millisecond precision, which i'm not seeing in the CI test as possible options. even doing a query in something like `select now()` in our database fails via connectorx. 

example timestamp:```2022-09-30 14:45:19.191``` 

seems like that timestamp in the buffer is eventually getting here and chopping off the first 7 characters: 
```
remaining buffer: Ok(
    "30 14:45:19.191",
)
```

it'd be great if we could have support to use timestamps with this precision.

**Comment by wseaton** [comment]
Ok, did far more research on this one than I should have (this turned out to be one of those fun ungoogleable errors). 

I believe in our case we have 2 seperate bugs in our postgres wire format implementation causing this that are not the fault of `connectorx` (or even `rust-postgres`).

1) Our postgres implementation is returning a bytestring that can't be serialized to i64 when doing the TIMESTAMP serialization. That is because it returns the actual timestamp value as an ASCII bytestring. 

    Ex. `2022-10-01 11:27:00.446`

    This causes the parse code to chomp the `year` of the timestamp, which looks like an int, and then the parsing code complains that the buffer is not properly drained because the rest of it is actually a string! This is definitely UB and the main issue.

2) for `now()` our implementation also returns the timestamp in what appears to be local time but without timezone (it's at least local for me, need to verify this more thoroughly). Even when the parsing code is correct, the result of this is that the concrete rust type we get back when round tripped is in a different timezone than the raw string from the database (I'm still not convinced there might not be a parsing bug w/ chrono here). While this phenomenon was initially noticed w/ `now()` it's still an annoyance for  all other `TIMESTAMP` columns.

via `cargo-patch` I was able to hack something together that appears to give us the desired behavior, but I highly doubt it is upstream-able:

```diff
diff --git a/postgres-protocol/Cargo.toml b/postgres-protocol/Cargo.toml
index a471690..5f507fa 100644
--- a/postgres-protocol/Cargo.toml
+++ b/postgres-protocol/Cargo.toml
@@ -19,3 +19,6 @@ memchr = "2.0"
 rand = "0.8"
 sha2 = "0.10"
 stringprep = "0.1"
+chrono = "0.4.22"
+time = {version = "0.3.14", features = ["std", "large-dates", "parsing"]}
+log = "0.4"
\ No newline at end of file
diff --git a/postgres-protocol/src/types/mod.rs b/postgres-protocol/src/types/mod.rs
index 05f515f..d66f6b9 100644
--- a/postgres-protocol/src/types/mod.rs
+++ b/postgres-protocol/src/types/mod.rs
@@ -1,12 +1,16 @@
 //! Conversions to and from Postgres's binary format for various types.
 use byteorder::{BigEndian, ByteOrder, ReadBytesExt};
 use bytes::{BufMut, BytesMut};
+use chrono::{DateTime, Local, TimeZone};
+use chrono::NaiveDateTime;
+use log::debug;
 use fallible_iterator::FallibleIterator;
 use std::boxed::Box as StdBox;
 use std::error::Error;
 use std::io::Read;
 use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};
-use std::str;
+use std::ops::{Add, Sub};
+use std::str::{self, FromStr};
 
 use crate::{write_nullable, FromUsize, IsNull, Lsn, Oid};
 
@@ -373,11 +377,23 @@ pub fn timestamp_to_sql(v: i64, buf: &mut BytesMut) {
 ///
 /// The value represents the number of microseconds since midnight, January 1st, 2000.
 #[inline]
-pub fn timestamp_from_sql(mut buf: &[u8]) -> Result<i64, StdBox<dyn Error + Sync + Send>> {
-    let v = buf.read_i64::<BigEndian>()?;
-    if !buf.is_empty() {
-        return Err("invalid message length: timestamp not drained".into());
-    }
+pub fn timestamp_from_sql(buf: &[u8]) -> Result<i64, StdBox<dyn Error + Sync + Send>> {
+    let s = str::from_utf8(buf).map_err(|_| "invalid timestamp")?;
+    debug!("raw datestring: {s}");
+    // write a format string for 2022-09-30 14:45:19.191
+    let fmt: &str = "%Y-%m-%d%_H:%M:%S%.3f";
+    // parse the timestamp into a naive date time with format
+    let naive = NaiveDateTime::parse_from_str(
+        s,
+        fmt,
+    )?;
+    // adding a 8 hour offset because parsing is weird and I don't know why
+    let naive = naive.add(chrono::Duration::hours(8));
+    // convert the naive date time to a chrono date time
+    let local: DateTime<Local> = Local.from_local_datetime(&naive).unwrap();
+    // substract 30 years in milliseconds to convert from unix epoch to postgres epoch
+    let v = local.sub(chrono::Duration::milliseconds(946728000000)).timestamp_micros() as i64;
+    // return in microseconds
     Ok(v)
 }
```

To replicate this I just ran the query:
```sql
select now();
```

Even if 1) could be fixed on our end (it likely can't), we'd need to rely on some custom parsing logic to solve for 2). I think the easiest solution is to tell our users to cast to string and rely on their dataframe library of choice to do timestamp coercion.
