### ISSUE TITLE
postgresql "SELECT 'x'" where x is character string fails without specifying type conversion

### ISSUE THREAD

**Issue by mcrumiller** [sfu-db/connector-x#369]
#### What language are you using?

**Python** 3.9.5

#### What database are you using?

PostgreSQL, Oracle, MSSQL Server

#### Can you describe your bug?

Selecting a constant string fails unless the string type (text/varchar/char) is specified.

#### What are the steps to reproduce the behavior?

```python
import connectorx as cx
conn = ... # setup your connection string
cx.read_sql(conn, "SELECT 1 AS value")            # suceeds
cx.read_sql(conn, "SELECT True AS value")         # suceeds
cx.read_sql(conn, "SELECT 'Y' AS value")          # fails
cx.read_sql(conn, "SELECT 'Y'::CHAR AS value")    # succeeds
cx.read_sql(conn, "SELECT 'Y'::VARCHAR AS value") # succeeds
cx.read_sql(conn, "SELECT 'Y'::TEXT AS value")    # succeeds
```

#### What is the error?

```
thread '<unnamed>' panicked at 'not implemented: unknown', D:\a\connector-x\connector-x\connectorx\src\sources\postgres\typesystem.rs:100:22
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Projects\project-slim\venv_slim\lib\site-packages\connectorx\__init__.py", line 224, in read_sql
    result = _read_sql(
pyo3_runtime.PanicException: not implemented: unknown
```

Show the error result here.

**Comment by wangxiaoying** [comment]
Hi @mcrumiller , that's weird I tried query `SELECT 'Y' AS a` on my local postgres instance in it works with the following result:
<img width="152" alt="image" src="https://user-images.githubusercontent.com/5569610/194189644-c729c2f6-f56b-4da2-8b96-2b9c4b5c74b9.png">

Is it related to the setup of the db? I'm using [official docker image of postgres](https://hub.docker.com/_/postgres) locally.

**Comment by mcrumiller** [comment]
@wangxiaoying that is odd indeed. I'll add that I'm using Greenplum, which is a fork of Postgres.
