### ISSUE TITLE
ModuleNotFoundError: No module named 'connectorx.connectorx_python' in Win10 with python 3.11

### ISSUE THREAD

**Issue by XU-99** [sfu-db/connector-x#418]
#### What language are you using?

Python3.11

#### What version are you using?

0.2.4a3

#### What database are you using?

MySQL

#### What dataframe are you using?

Pandas

#### Can you describe your bug?

When I import connectorx to python, it shows "No module named 'connectrox.connectrox_python'"

#### What are the steps to reproduce the behavior?

import connectorx

##### Database setup if the error only happens on specific data or data type

Table schema and example data

##### Example query / code

```
import connectorx

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    import connectorx
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\connectorx\__init__.py", line 3, in <module>
    from .connectorx_python import read_sql as _read_sql
ModuleNotFoundError: No module named 'connectorx.connectorx_python'

```

#### What is the error?

Show the error result here.

**Comment by XU-99** [comment]
I downgraded the python version to 3.10 and it works, very usful tool. Thanks soooo much!!!!
