### ISSUE TITLE
Can not install connector-x through PyPI.

### ISSUE THREAD

**Issue by Duoquote** [sfu-db/connector-x#428]
#### What language are you using?

**Python**

#### What version are you using?

0.3.1

#### Can you describe your bug?

Can not install connector-x through PyPI.

#### What are the steps to reproduce the behavior?

```bash
pip install connectorx
```

Not sure if the issue is related to the package or the issue is on PyPI, so I created [this issue](https://github.com/pypi/support/issues/2512) on PyPI support and wanted to let know this repo that there is an issue while installing this specific package.

Installs with no problem with, Python 3.9.13 and pip 22.3 from C:\Users\duoqu\miniconda3\envs\tf\lib\site-packages\pip (python 3.9)
```console
Collecting connectorx
  Downloading connectorx-0.3.1-cp39-none-win_amd64.whl (41.3 MB)
     ---------------------------------------- 41.3/41.3 MB 8.7 MB/s eta 0:00:00
Installing collected packages: connectorx
Successfully installed connectorx-0.3.1
```

But for Python 3.8.5 and 3.7 (pip 22.1.2 from C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip (python 3.8))
```console
Collecting connectorx
  Downloading connectorx-0.3.1-cp38-none-win_amd64.whl (41.3 MB)
     ---- ----------------------------------- 4.2/41.3 MB 5.2 MB/s eta 0:00:08
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_vendor\urllib3\response.py", line 435, in _error_catcher
    yield
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\commands\install.py", line 341, in run
    requirement_set = resolver.resolve(
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 291, in __init__
    super().__init__(
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\operations\prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\operations\prepare.py", line 473, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\operations\prepare.py", line 155, in unpack_url
    file = get_http_url(
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\operations\prepare.py", line 96, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\network\download.py", line 146, in __call__
    for chunk in chunks:
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_vendor\urllib3\response.py", line 538, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\duoqu\miniconda3\envs\junk\lib\site-packages\pip\_vendor\urllib3\response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

#### What is the error?

The full error on my server:
```bash
root@server:/server# pip3 install -r requirements.txt
Obtaining jenks from git+https://github.com/perrygeo/jenks.git@80b2557d635ba4a0640157d3616b50dbf39c2221#egg=jenks (from -r requirements.txt (line 15))
  Skipping because already up-to-date.
  Preparing metadata (setup.py) ... done
Collecting chroma@ git+https://github.com/Duoquote/Chroma.git
  Cloning https://github.com/Duoquote/Chroma.git to /tmp/pip-install-gmaov0i7/chroma_415d112fecc84b3d93360fd7fe36c97c
  Running command git clone --filter=blob:none --quiet https://github.com/Duoquote/Chroma.git /tmp/pip-install-gmaov0i7/chroma_415d112fecc84b3d93360fd7fe36c97c
  Resolved https://github.com/Duoquote/Chroma.git to commit a4f1985649b922c6f673b44b39b8eb0f795edeba
  Preparing metadata (setup.py) ... done
Collecting Django==3.0.5
  Using cached Django-3.0.5-py3-none-any.whl (7.5 MB)
Collecting geopandas==0.9.0
  Using cached geopandas-0.9.0-py2.py3-none-any.whl (994 kB)
Collecting python_docx==0.8.10
  Using cached python-docx-0.8.10.tar.gz (5.5 MB)
  Preparing metadata (setup.py) ... done
Collecting pandas==1.3.5
  Using cached pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
Collecting Shapely==1.8.1.post1
  Using cached Shapely-1.8.1.post1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.0 MB)
Collecting spectra==0.0.11
  Using cached spectra-0.0.11.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting folium==0.11.0
  Using cached folium-0.11.0-py2.py3-none-any.whl (93 kB)
Collecting pyproj==2.6.1.post1
  Using cached pyproj-2.6.1.post1-cp37-cp37m-manylinux2010_x86_64.whl (10.9 MB)
Collecting pypolyline==0.1.7
  Using cached pypolyline-0.1.7-py2.py3-none-manylinux1_x86_64.whl (540 kB)
Requirement already satisfied: GDAL==2.4.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 12)) (2.4.0)
Collecting djangorestframework==3.12.1
  Using cached djangorestframework-3.12.1-py3-none-any.whl (913 kB)
Collecting docx==0.2.4
  Using cached docx-0.2.4.tar.gz (54 kB)
  Preparing metadata (setup.py) ... done
Collecting Unidecode==1.1.1
  Using cached Unidecode-1.1.1-py2.py3-none-any.whl (238 kB)
Collecting urllib3==1.26.0
  Using cached urllib3-1.26.0-py2.py3-none-any.whl (136 kB)
Collecting requests==2.25.0
  Using cached requests-2.25.0-py2.py3-none-any.whl (61 kB)
Collecting selenium==3.141.0
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting nanoid==2.0.0
  Using cached nanoid-2.0.0-py3-none-any.whl (5.8 kB)
Collecting xlrd==1.2.0
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Collecting polyline==1.4.0
  Using cached polyline-1.4.0-py2.py3-none-any.whl (4.4 kB)
Collecting openpyxl==3.0.5
  Using cached openpyxl-3.0.5-py2.py3-none-any.whl (242 kB)
Collecting xlsxwriter==1.3.7
  Using cached XlsxWriter-1.3.7-py2.py3-none-any.whl (144 kB)
Collecting psycopg2==2.8.6
  Using cached psycopg2-2.8.6.tar.gz (383 kB)
  Preparing metadata (setup.py) ... done
Collecting connectorx==0.3.1
  Downloading connectorx-0.3.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (46.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━ 29.4/46.6 MB 37.5 MB/s eta 0:00:01
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/urllib3/response.py", line 560, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/urllib3/response.py", line 526, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.7/http/client.py", line 461, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 401, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
    version=version,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    version=version,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/prepare.py", line 542, in _prepare_linked_requirement
    hashes,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/prepare.py", line 170, in unpack_url
    hashes=hashes,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/network/utils.py", line 87, in response_chunks
    decode_content=False,
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/urllib3/response.py", line 621, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/urllib3/response.py", line 586, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/urllib3/response.py", line 442, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
root@server:/server#
```

**Comment by Duoquote** [comment]
It was an issue on PyPI servers, and is solved [here](https://github.com/pypi/support/issues/2512).
